//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodemashApp.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JsonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal JsonResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodemashApp.Resources.JsonResources", typeof(JsonResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  [
        ///    {
        ///        &quot;Id&quot;: 1,
        ///        &quot;SessionStartTime&quot;: &quot;2015-01-08T08:00:00&quot;,
        ///        &quot;SessionEndTime&quot;: &quot;2015-01-08T09:00:00&quot;,
        ///        &quot;Rooms&quot;: [
        ///            &quot;Zambezi&quot;,
        ///            &quot;Nile&quot;
        ///        ],
        ///        &quot;Title&quot;: &quot;Sample String 1&quot;,
        ///        &quot;Abstract&quot;: &quot;Sample long string&quot;,
        ///        &quot;SessionType&quot;: &quot;Regular Session&quot;,
        ///        &quot;Tags&quot;: [
        ///            &quot;Mobile&quot;
        ///        ],
        ///        &quot;Speakers&quot;: [
        ///            {
        ///                &quot;Id&quot;: &quot;fce6393b-0186-431f-be91-85ebd2ee453f&quot;,
        ///                &quot;FirstName&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PublicSessionDataModel {
            get {
                return ResourceManager.GetString("PublicSessionDataModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  [
        ///    {
        ///        &quot;Id&quot;: &quot;a02a0671-98a9-4365-a7b5-b963c6b4b046&quot;,
        ///        &quot;FirstName&quot;: &quot;Sample String 1&quot;,
        ///        &quot;LastName&quot;: &quot;Sample String 2&quot;,
        ///        &quot;Biography&quot;: &quot;A (potentially) really long Sample String&quot;,
        ///        &quot;GravatarUrl&quot;: &quot;//www.gravatar.com/avatar/06f6516772eca8763479753e2746e328&quot;,
        ///        &quot;TwitterLink&quot;: null,
        ///        &quot;GitHubLink&quot;: null,
        ///        &quot;LinkedInProfile&quot;: null,
        ///        &quot;BlogUrl&quot;: null
        ///    },
        ///    {
        ///        &quot;Id&quot;: &quot;0d77e7b9-8315-4197-a135-6091933cbda0&quot;,
        ///        &quot;FirstName&quot;: &quot;Sam [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PublicSpeakerDataModel {
            get {
                return ResourceManager.GetString("PublicSpeakerDataModel", resourceCulture);
            }
        }
    }
}
